---
title: "Overview"
output: html_document
---

> The Bali sardine is the predominant species caught by the sardine fisheries of the Philippines and is an extremely important resource. The purpose of this application is to allow policy makers and fishery managers in the Philippines to explore the potential implications of different management strategies for the Bali sardine fishery.

This application provides a simple interactive tool for evaluating the potential effectiveness of managing the Bali sardine (*S. lemuru*) fishery with a closed season. A biological model simulates potential catch and biomass implications of different management strategies relative to the status quo given a user-defined representation of the current status of the fishery. 

The application contains the following components (tabs):

1. **Overview**
2. **The Fishery** - Description of the *S. lemuru* fishery and the recorded catch history
3. **Parameters** - User-defined settings for the fishery model, including life-history parameters, current depletion, initial recruitment, and simulation length
3. **Fishery Model** - Biological model of the *S. lemuru* fishery
4. **Methods** - Description of modeling methods
